#!/usr/bin/env python3
"""Validate README references to final/comparison report artifacts.

The README should link stable, small report summaries. Bulky generated DBs and
raw run directories should be regenerated by command instead of becoming README
link targets.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]
README = REPO_ROOT / "README.md"

REQUIRED_ARTIFACTS = [
    "reports/final/intended_tool_quality_gate.md",
    "reports/final/intended_tool_quality_gate.json",
    "reports/final/manual_relation_precision.md",
    "reports/final/manual_relation_precision.json",
    "reports/final/comprehensive_benchmark_latest.md",
    "reports/final/comprehensive_benchmark_latest.json",
    "reports/comparison/codegraph_vs_cgc_latest.md",
    "reports/comparison/codegraph_vs_cgc_latest.json",
]

MARKDOWN_LINK_RE = re.compile(r"(?<!!)\[[^\]]+\]\(([^)\n]+)\)")
REPORT_PATH_RE = re.compile(
    r"reports[\\/](?:final|comparison)[\\/][A-Za-z0-9_.\\/\-]+(?:\.md|\.json|\.jsonl)"
)


def split_target(raw: str) -> str:
    target = raw.strip()
    if target.startswith("<"):
        end = target.find(">")
        if end != -1:
            return target[1:end]
    for quote in (' "', " '"):
        pos = target.find(quote)
        if pos != -1:
            target = target[:pos]
    return target.split("#", 1)[0].strip()


def case_sensitive_exists(path: Path) -> bool:
    if not path.exists():
        return False
    try:
        rel = path.resolve().relative_to(REPO_ROOT.resolve())
    except ValueError:
        return False
    current = REPO_ROOT.resolve()
    for part in rel.parts:
        names = {entry.name: entry for entry in current.iterdir()}
        if part not in names:
            return False
        current = names[part]
    return True


def normalize(path: str) -> str:
    return path.strip().replace("\\", "/").strip(".,;:)")


def readme_report_paths(text: str) -> set[str]:
    paths: set[str] = set()

    for match in MARKDOWN_LINK_RE.finditer(text):
        target = normalize(split_target(match.group(1)))
        if target.startswith(("reports/final/", "reports/comparison/")):
            paths.add(target)

    for match in REPORT_PATH_RE.finditer(text):
        paths.add(normalize(match.group(0)))

    return paths


def validate() -> int:
    text = README.read_text(encoding="utf-8")
    paths = readme_report_paths(text)
    errors: list[str] = []

    for required in REQUIRED_ARTIFACTS:
        if required not in paths:
            errors.append(f"README does not reference required artifact `{required}`")

    for path in sorted(paths):
        if "/artifacts/" in path:
            errors.append(
                f"README links generated raw artifact `{path}`; link a stable report or document regeneration instead"
            )
            continue
        target = REPO_ROOT / path
        if not case_sensitive_exists(target):
            errors.append(f"README artifact path is missing or case-mismatched: `{path}`")

    if errors:
        for error in errors:
            print(f"ERROR: {error}", file=sys.stderr)
        print(f"README report paths found: {len(paths)}", file=sys.stderr)
        return 1

    print(f"README artifact check passed: {len(paths)} report paths checked")
    return 0


if __name__ == "__main__":
    raise SystemExit(validate())
